[package]
name = "zerompk-wasm32-tests"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zerompk = { path = "../../zerompk", default-features = false, features = ["derive"] }

[profile.release]
opt-level = 3
overflow-checks = false
panic = "abort"

[workspace]
