name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install nightly --profile minimal -c rustfmt -c clippy
      - run: cargo +nightly fmt --all --check
      - run: cargo +nightly clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install nightly --profile minimal
      - run: cargo +nightly test -p zerompk --lib --tests # skip doc tests since they requires the derive feature
      - run: cargo +nightly test -p zerompk --features derive
      - run: cargo +nightly test -p zerompk_derive
